### PR TITLE
Update README.md for Windows users.

### PR DESCRIPTION
**Pull request by tdawry**
Added directory location for Windows users.

### CODE REVIEW

**Comment by tdawry** [comment]
The [RStudio blog post regarding custom theme support](https://blog.rstudio.com/2018/10/29/rstudio-ide-custom-theme-support/) appears to use a different directory structure than I am seeing on my end.

> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

**Comment by batpigandme** [comment]
🤔 Now that you can directly import an `.rstheme` file, that whole part of the README can probably go, actually. When I first made the theme, there wasn't direct import yet.

**Comment by tdawry** [comment]
Also here, https://rstudio.github.io/rstudio-extensions/rstudio-theme-creation.html .

**Comment by batpigandme** [comment]
Yeah. If you want to file an issue about updating the README re rstheme installation, that'd be great. I need to take a closer look when I'm not on my phone!

**Comment by tdawry** [comment]
I have created an issue [here](https://github.com/rstudio/rstudio/issues/6081).

**Pull request closed without merging**
